### ISSUE TITLE
NeonPage subcomponents don't inherit NEON Theme separately

### ISSUE THREAD

**Issue by arbolitoloco** [NEONScience/portal-core-components#2]
So I was trying to render just a few components of NeonPage, and I'm a little lost to how the default Theme should be applied to separate components. 

When I render [NeonUtilityBar](https://github.com/NEONScience/portal-core-components/tree/master/src/lib_components/components/NeonUtilityBar) or [NeonHeader](https://github.com/NEONScience/portal-core-components/tree/master/src/lib_components/components/NeonHeader), for instance, by themselves (not in NeonPage), I don't get the styling offered by the Theme. 

I understand more or less what to do if I'd like to define custom styles (call style builder from within Material-UI, right?), but how can I apply default Theme styles to a "standalone" component? Thanks!

**Comment by Frencil** [comment]
@arbolitoloco this may be because you need a `ThemeProvider`.

Material UI applies [Themes](https://material-ui.com/customization/theming/) by way of wrapping a DOM tree in a `<ThemeProvider>` tag with the theme provided as a prop. See the documentation there... ThemeProviders _can_ be nested but I've honestly not used nested theming yet. As a rule of thumb you should usually have exactly one ThemeProvider for every theme you intend to use.

You can see where NeonPage invokes the ThemeProvider [here](https://github.com/NEONScience/portal-core-components/blob/80f32dbc1bdb126f03a68ba93a1fdace2df1e521/src/lib_components/components/NeonPage/NeonPage.jsx#L173). Note that it's at the root of the DOM tree (NeonHeader, NeonFooter, and all page content are inside the ThemeProvider). If you're not wanting to use NeonPage but do want to use the other themed components you should be able to achieve the desired effect by wrapping your DOM tree in a ThemeProvider with the theme plugged in at the highest level. Note this may affect some of the visual presentation of other elements on your pages. If that's not what you want then you can wrap individual elements or blocks of elements in a ThemeProvider, but in general fewer ThemeProviders spread throughout the code is better.
